FROM pytorch/pytorch:1.11.0-cuda11.3-cudnn8-devel


RUN pip install --default-timeout=1000 --no-cache-dir -U albumentations 
RUN pip install --default-timeout=1000 --no-cache-dir -U rich
RUN pip install --default-timeout=1000 --no-cache-dir jupyter seaborn pytorch-lightning

